/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_project_rapid_gvirtus4j_Buffer */

#ifndef _Included_eu_project_rapid_gvirtus4j_Buffer
#define _Included_eu_project_rapid_gvirtus4j_Buffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_project_rapid_gvirtus4j_Buffer
 * Method:    prepareFloat
 * Signature: ([F)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_eu_project_rapid_gvirtus4j_Buffer_prepareFloat
  (JNIEnv *, jclass, jfloatArray);

/*
 * Class:     eu_project_rapid_gvirtus4j_Buffer
 * Method:    preparePtxSource
 * Signature: (Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_eu_project_rapid_gvirtus4j_Buffer_preparePtxSource
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     eu_project_rapid_gvirtus4j_Buffer
 * Method:    prepareSingleByte
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_eu_project_rapid_gvirtus4j_Buffer_prepareSingleByte
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
